Ignore spec files to allow for co-located tests
actionhero/actionhero pull request #2309
Opened 2022-10-04 04:12 UTC by okcoker

Instead of having all my tests under `__tests__`, I wanted to co-locate them alongside my src files (ie `actions/status.ts` and `actions/status.test.ts`). I had a passing test suite when I had everything under `__tests__` but after moving to a co-located folder structure, my test suite failed with cryptic errors.

This seems to fix that.

2022-10-04 22:47 UTC, evantahler requested changes

2022-10-04 22:47 UTC, evantahler commented on __tests__/modules/utils/ensureNoTsHeaderOrSpecFiles.ts
> +    ]);
Can you please add one more test case asserting that `test-my-api.js` or something like that is still OK (that `.test.` is what is ignored).

2022-10-04 22:47 UTC, evantahler commented on __tests__/modules/utils/ensureNoTsHeaderOrSpecFiles.ts
> +    ]);
Otherwise, this PR is 👍!

2022-10-05 01:24 UTC, okcoker commented on __tests__/modules/utils/ensureNoTsHeaderOrSpecFiles.ts
> +    ]);
Done!

2022-10-05 18:02 UTC, evantahler approved these changes
🥳

2022-10-05 18:09 UTC, merged

2022-10-05 18:18 UTC, evantahler commented
released! https://github.com/actionhero/actionhero/releases/tag/v28.2.0