Pass options to form contructor
actionhero/actionhero pull request #2640
Opened 2023-11-02 09:44 UTC by 321hendrik

As described [here](https://github.com/node-formidable/formidable#formidable--incomingform) options for IncomingForm should be passed to the contructor directly.

2023-11-03 01:08 UTC, evantahler requested changes

2023-11-03 01:08 UTC, evantahler commented on src/servers/web.ts
> +        connection.rawConnection.form = new formidable.IncomingForm(this.config.formOptions);
Good catch! I like this change on principal.  

since this value is coming from [config](https://github.com/actionhero/actionhero/blob/main/src/config/web.ts#L81-L86), there is a chance it could be null or undefined, or even an empty object.  Could you test for that?

2023-11-03 01:16 UTC, evantahler commented
Also, note the linter error

2023-11-17 01:46 UTC, evantahler commented
Ping! Are you still interested in working on this?

2023-11-28 10:27 UTC, 321hendrik commented
Sorry, I couldn't spend time on this for a while. I made the requested changes and also added a type to the options for code intellisense.

2023-11-28 10:30 UTC, 321hendrik commented on src/servers/web.ts
> +        connection.rawConnection.form = new formidable.IncomingForm(this.config.formOptions);
I added a check and fixed the linter error.

2023-12-02 01:26 UTC, merged

2023-12-02 01:29 UTC, evantahler commented
Released in https://github.com/actionhero/actionhero/releases/tag/v29.1.0